language: java

jdk:
  - openjdk8

script:
  - mvn clean test

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: script
  script: .travis/release.sh
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8